# Generated by Django 5.1.3 on 2024-12-03 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamo', '0002_prestamo_descripcion_alter_prestamo_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('cancelado', 'Cancelado'), ('atrasado', 'Atrasado')], default='activo', max_length=10),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='saldo_actual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
