# Generated by Django 5.1.3 on 2024-12-03 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamo', '0004_notificacion_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='metodo_pago',
            field=models.CharField(choices=[('Efectivo', 'Efectivo'), ('Tarjeta de Crédito', 'Tarjeta de Crédito'), ('Tarjeta de Débito', 'Tarjeta de Débito'), ('Transferencia Bancaria', 'Transferencia Bancaria'), ('Otro', 'Otro')], max_length=50),
        ),
    ]
