# Generated by Django 5.1.3 on 2024-12-05 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prestamo', '0005_alter_pago_metodo_pago'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notificacion',
        ),
    ]
